// AutoManager WebManager (automanager.com) — the website half of a used-car
// DMS, running mostly small independents. Its rooftops sat in
// needs-investigation because the pages carry no JSON-LD at all: no ItemList
// on the SRP, no Vehicle on the VDP, nothing for the generic stack to read.
// Measured 2026-08-23 on a seeded random 400 of the written-off pile, 7 rows
// were AutoManager — the largest unbuilt vendor cohort in that sample, ~64
// rows across the pile if the rate holds.
//
// Everything is server-rendered and the platform's own markup is regular. Each
// SRP tile is a `inventory-panel` div whose attributes are generated by the
// platform rather than by the rooftop's theme:
//
//   data-id, data-displaytitle, data-displaymake, data-displaymodel,
//   data-displaytrim, data-displayyear, data-displayengine,
//   data-displaytransmission, data-displaymileage, data-displayextcolor,
//   data-displayintcolor, data-displaydrivetrain, data-displayfuel,
//   data-displayphoto
//
// VIN and price are not attributes; they are inside the tile, in the
// theme-configurable detail block (`<span class="vin">`) and price container.
//
// THE PRICE IS THE RENDERED ONE, and this is the trap here. Tiles also carry a
// CarGurus badge with `data-cg-vin` and `data-cg-price`, which looks like a
// clean machine-readable price and is not one: on crescentauto.net the Kia
// Sportage tile renders "Internet Price $10,500" while its badge says
// data-cg-price="10990.0000" — $490 apart on the same car, in the same tile,
// on the same request. (On another tile in that same page they agree, which
// is exactly what makes it dangerous.) The badge is a third party's number.
// Only the price the dealer prints is this listing's asking price.
//
// And when a tile prints MORE THAN ONE distinct price, this abstains rather
// than pick one. Every rooftop sampled so far shows a single "Internet Price"
// line, so there is no observed ladder to resolve, and inventing a precedence
// for a ladder nobody has seen is how the dealer.com internetPrice rule
// overstated 1,256 live listings. No price is a state ingest.mjs already
// handles; a wrong one costs a shopper.
//
// Condition is NOT emitted. The panel has no new/used token, the VDP path
// (/vehicle-details/{slug}-{id}) has none either, and this platform's rooftops
// are mostly used-only independents — which is a reason to expect "used", not
// evidence of it. See ../condition.mjs: an absent field became "used" once
// already and published 150 new cars as used.
import { AUTOMANAGER_PRICE } from "../price-provenance.mjs";
import { stabilizeImages } from "../images.mjs";

const ASSET_RE = /automanagerprodcdn\.azureedge\.net|automanager\.blob\.core\.windows\.net|wm\.automanager\.com/i;

export function isAutoManager(html) {
  return typeof html === "string" && ASSET_RE.test(html);
}

export const AUTOMANAGER_SRP_PATH = "/view-inventory";

export function autoManagerSeeds(origin) {
  return [origin + AUTOMANAGER_SRP_PATH];
}

// Pagination is a plain server-side ?page=N; the SRP publishes every page
// number in its pager. Walk to the highest one.
export function autoManagerNextPageUrl(html, pageUrl) {
  if (typeof html !== "string") return null;
  const pages = [...html.matchAll(/[?&]page=(\d{1,4})\b/g)].map((m) => Number(m[1]));
  if (!pages.length) return null;
  let u;
  try {
    u = new URL(pageUrl);
  } catch {
    return null;
  }
  const cur = Number(u.searchParams.get("page") ?? 1);
  if (!Number.isFinite(cur) || cur >= Math.max(...pages)) return null;
  u.searchParams.set("page", String(cur + 1));
  return u.toString();
}

const VIN_RE = /^[A-HJ-NPR-Z0-9]{17}$/;
const PANEL_RE = /<div class="[^"]*\binventory-panel\b[^"]*"[^>]*>/g;

const num = (v) => {
  if (v == null) return undefined;
  const n = Number(String(v).replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) && n > 0 ? n : undefined;
};
const attr = (chunk, name) => {
  const v = chunk.match(new RegExp(`\\bdata-${name}="([^"]*)"`))?.[1];
  return v && v.trim() ? v.trim() : undefined;
};

/** Every distinct price the tile prints, as numbers. More than one means this
 *  rooftop shows a ladder and we do not know which rung is the ask. */
export function tilePrices(chunk) {
  const seen = new Set();
  for (const m of chunk.matchAll(/class="pricevalue\d[^"]*"[^>]*>([\s\S]{0,200}?)<\/div>/g)) {
    const n = num(m[1].replace(/<[^>]+>/g, ""));
    if (n != null) seen.add(n);
  }
  return [...seen];
}

function tileVehicle(chunk, pageUrl) {
  // The tile's own detail block first; the CarGurus badge's VIN is the
  // fallback, and only for identity — never for its price (see header).
  const vin = (
    chunk.match(/class="vin"[^>]*>\s*([A-HJ-NPR-Z0-9]{17})\s*</)?.[1] ??
    chunk.match(/data-cg-vin="([A-HJ-NPR-Z0-9]{17})"/)?.[1] ??
    ""
  ).toUpperCase();
  if (!VIN_RE.test(vin)) return null;

  const href = chunk.match(/href="([^"]*\/vehicle-details\/[^"#]+)"/)?.[1];
  let url;
  try {
    url = href ? new URL(href, pageUrl).toString() : undefined;
  } catch {}

  const prices = tilePrices(chunk);
  const price = prices.length === 1 ? prices[0] : undefined;

  // data-displayphoto is the theme's "coming soon" graphic when the rooftop
  // has uploaded no photos (a 2019 Model 3 on concoursnj.com shipped one as
  // its card image). That is a picture of nothing, so no image is the honest
  // answer — the card already handles a listing with none.
  const photo = attr(chunk, "displayphoto");
  const images = stabilizeImages(photo && !/\/wmthemes\/images\/.*comingsoon/i.test(photo) ? [photo] : []);
  const mileage = num(attr(chunk, "displaymileage"));
  // The dealer's own fuel string, untouched — classifyEv decides.
  const fuel = attr(chunk, "displayfuel");

  return {
    "@type": "Vehicle",
    vehicleIdentificationNumber: vin,
    vehicleModelDate: attr(chunk, "displayyear"),
    brand: attr(chunk, "displaymake"),
    model: attr(chunk, "displaymodel"),
    vehicleConfiguration: attr(chunk, "displaytrim"),
    name: attr(chunk, "displaytitle"),
    mileageFromOdometer: mileage != null ? { "@type": "QuantitativeValue", value: mileage } : undefined,
    color: attr(chunk, "displayextcolor"),
    vehicleInteriorColor: attr(chunk, "displayintcolor"),
    driveWheelConfiguration: attr(chunk, "displaydrivetrain"),
    vehicleTransmission: attr(chunk, "displaytransmission"),
    sku: chunk.match(/class="stocknumber"[^>]*>\s*([^<]{1,32}?)\s*</)?.[1] || undefined,
    image: images.length ? images : undefined,
    fuelType: fuel,
    vehicleEngine: { "@type": "EngineSpecification", name: attr(chunk, "displayengine"), fuelType: fuel },
    offers: {
      "@type": "Offer",
      price,
      priceProvenance: price != null ? AUTOMANAGER_PRICE : undefined,
      priceCurrency: "USD",
      url,
    },
  };
}

/** Every car on an AutoManager SRP page. Tiles with no VIN are skipped:
 *  crawl.mjs keys a VIN-less record by its source URL and every tile on a page
 *  shares one, so emitting them would collapse the page to a single car. */
export function autoManagerVehicles(html, pageUrl) {
  if (!isAutoManager(html)) return [];
  const starts = [...html.matchAll(PANEL_RE)].map((m) => m.index);
  const out = [];
  const seen = new Set();
  for (let i = 0; i < starts.length; i++) {
    const chunk = html.slice(starts[i], starts[i + 1] ?? html.length);
    const v = tileVehicle(chunk, pageUrl);
    if (!v || seen.has(v.vehicleIdentificationNumber)) continue;
    seen.add(v.vehicleIdentificationNumber);
    out.push(v);
  }
  return out;
}
